version: '2'  
services:  
  web:
    container_name: web
    build: ./serverless-code
    ports:
     - "3000:3000"
     - "8000:8000"
    depends_on:
     - kinesis
    volumes:
     - ~/.aws/:/root/.aws:ro
    environment:
     # Environment variables to configure the app on startup.
     - DYNAMO_HOST=localhost
     - KINESIS_HOST=kinesis

  kinesis:
    container_name: kinesalite
    image: instructure/kinesalite
    ports:
     - "4567:4567"

  kinesis-consumer:
    container_name: kinesis-consumer
    build:
      context: ./serverless-code
      dockerfile: Dockerfile.kinesis
    restart: always
    environment:
     # Environment variables to configure the app on startup.
     - IS_RUN_KINESIS_LAMBDA_RUNNER=true
     - STREAM_NAME=dev-data-receiver
     - KINESIS_ENDPOINT=http://kinesis:4567/
    depends_on:
     - kinesis
