version: '2'  
services:  
  web:
    container_name: web
    build: ./serverless-code
    ports:
     - "3000:3000"
    depends_on:
     - db
    volumes:
     - ~/.aws/:/root/.aws:ro
    environment:
     # Environment variables to configure the app on startup.
     - DYNAMO_HOST=db
  db:
    container_name: db
    build: ./serverless-dynamodb
    ports:
     - "8000:8000"
    volumes:
     - ../serverless-code/offline/:/app/offline